spring.application.name=hr-backend
server.port=8081

# Keycloak Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/hr-realm

# Keycloak Admin Configuration (for user registration)
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=hr-realm
keycloak.admin.username=admin
keycloak.admin.password=admin


# Keycloak Client Configuration (for login)

keycloak.client-id=hr-backend
keycloak.client-secret=FvRGlYkyvb7XcJNSgRqTpmtdRxWbSWDZ
# PostgreSQL Database Configuration

# Default PostgreSQL port is 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

